export const slider2=[{
    "id": 3708,
    "title": "Princess Farmer (Mobile) Giveaway",
    "worth": "$5.99",
    "thumbnail": "https://www.gamerpower.com/offers/1/6a4fbccf3c77e.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6a4fbccf3c77e.jpg",
    "description": "Princess Farmer (Mobile version) is free until July 16 on the Epic Games Store App for iPhone, iPad, and Android.\r\n\r\nNote: May not be available in all regions",
    "instructions": "1. Click the button using your phone to visit the Epic Games Store mobile page.\r\n2. Install the Epic Games Store App on your Android or iOS device.\r\n3. Open the App, scroll down to the \"Free Games\" section and click on the giveaway banner.\r\n4. Install the game and have fun!",
    "open_giveaway_url": "https://www.gamerpower.com/open/princess-farmer-mobile-giveaway",
    "published_date": "2026-07-09 11:22:55",
    "type": "Game",
    "platforms": "Android, iOS",
    "end_date": "2026-07-16 23:59:00",
    "users": 5390,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/princess-farmer-mobile-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/princess-farmer-mobile-giveaway"
  },
  {
    "id": 3707,
    "title": "Tattoo Tycoon (Epic Games) Giveaway",
    "worth": "$29.99",
    "thumbnail": "https://www.gamerpower.com/offers/1/6a4fb9f42523a.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6a4fb9f42523a.jpg",
    "description": "Finally you can open your own tattoo parlor! Claim Tattoo Tycoon for free on the Epic Games Store. Tattoo Tycoon is a 3d management game where you become a tattoo artist and run your own shop.",
    "instructions": "1. Click the button to visit the giveaway page.\r\n2. Register or log in to your Epic Games Store account.\r\n3. Click the button to add the game to your library",
    "open_giveaway_url": "https://www.gamerpower.com/open/tattoo-tycoon-epic-games-giveaway",
    "published_date": "2026-07-09 11:10:44",
    "type": "Game",
    "platforms": "PC, Epic Games Store",
    "end_date": "2026-07-16 23:59:00",
    "users": 11090,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/tattoo-tycoon-epic-games-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/tattoo-tycoon-epic-games-giveaway"
  },
  {
    "id": 3706,
    "title": "Nova Lands (Epic Games) Giveaway",
    "worth": "$19.99",
    "thumbnail": "https://www.gamerpower.com/offers/1/6a4fb8cf73513.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6a4fb8cf73513.jpg",
    "description": "Start building your factory today! Grab Nova Lands for free via Epic Games Store! Nova Lands is a cool 2d factory building and island management game. Don´t miss it!",
    "instructions": "1. Click the button to visit the giveaway page.\r\n2. Register or log in to your Epic Games Store account.\r\n3. Click the button to add the game to your library",
    "open_giveaway_url": "https://www.gamerpower.com/open/nova-lands-epic-games-giveaway",
    "published_date": "2026-07-09 11:05:51",
    "type": "Game",
    "platforms": "PC, Epic Games Store",
    "end_date": "2026-07-16 23:59:00",
    "users": 11890,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/nova-lands-epic-games-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/nova-lands-epic-games-giveaway"
  },
  {
    "id": 3498,
    "title": "Primal Slideee Deluxe (Stove) Giveaway",
    "worth": "$1.99",
    "thumbnail": "https://www.gamerpower.com/offers/1/6993208da38c7.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6993208da38c7.jpg",
    "description": "Download Primal Slideee Deluxe for free via Stove until July 31!",
    "instructions": "1. Click the button to visit the giveaway page.\r\n2. Log in to your STOVE Store account.\r\n3. Click the button \"Cart\" to add the game to your library",
    "open_giveaway_url": "https://www.gamerpower.com/open/primal-slideee-deluxe-pc-giveaway",
    "published_date": "2026-07-08 11:25:07",
    "type": "Game",
    "platforms": "PC",
    "end_date": "2026-07-31 23:59:59",
    "users": 12010,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/primal-slideee-deluxe-pc-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/primal-slideee-deluxe-pc-giveaway"
  },
  {
    "id": 3704,
    "title": "GOALS: AMD Kit Key Giveaway",
    "worth": "N/A",
    "thumbnail": "https://www.gamerpower.com/offers/1/6a4becdd3a999.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6a4becdd3a999.jpg",
    "description": "Claim your free key with the AMD Advanced Kit and enjoy GOALS in style. Please note the base game GOALS (free-to-play) is required to enjoy this DLC content.",
    "instructions": "1. Create or log in to your free AMD account.\n2. Connect one account to your AMD Account (Twitch, Google or Microsoft)\n3. Click the button to unlock your key.\n4. Follow the giveaway instructions to redeem your key.",
    "open_giveaway_url": "https://www.gamerpower.com/open/goals-amd-kit-steam-key-giveaway",
    "published_date": "2026-07-06 13:58:53",
    "type": "DLC",
    "platforms": "PC, Steam",
    "end_date": "N/A",
    "users": 4560,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/goals-amd-kit-steam-key-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/goals-amd-kit-steam-key-giveaway"
  },
  {
    "id": 3306,
    "title": "Whiskey Mafia: Frank's Story (IndieGala) Giveaway",
    "worth": "$5.99",
    "thumbnail": "https://www.gamerpower.com/offers/1/68dd2161c3088.jpg",
    "image": "https://www.gamerpower.com/offers/1b/68dd2161c3088.jpg",
    "description": "Download Whiskey Mafia: Frank's Story for free on IndieGala! Whiskey Mafia: Frank's Story is a 2D adventure game where you experience life in the mafia.",
    "instructions": "1. Click the button to visit the giveaway page.\r\n2. Login into your free IndieGala account.\r\n3. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n4. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/whiskey-mafia-frank-s-story",
    "published_date": "2026-07-03 08:46:33",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 65760,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/whiskey-mafia-frank-s-story",
    "open_giveaway": "https://www.gamerpower.com/open/whiskey-mafia-frank-s-story"
  },
  {
    "id": 3294,
    "title": "Whiskey.Mafia. Leo's Family (IndieGala) Giveaway",
    "worth": "$5.99",
    "thumbnail": "https://www.gamerpower.com/offers/1/68d3cbf0cfcb7.jpg",
    "image": "https://www.gamerpower.com/offers/1b/68d3cbf0cfcb7.jpg",
    "description": "Get a free copy of Whiskey.Mafia. Leo's Family via IndieGala! Whiskey.Mafia. Leo's Family is a indie 2d adventure game with cool pixel art and a non-linear plot. Check it out",
    "instructions": "1. Click the button to visit the giveaway page.\r\n2. Login into your free IndieGala account.\r\n3. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n4. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/whiskey-mafia-leo-s-family-pc-giveaway",
    "published_date": "2026-07-03 08:45:22",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 67470,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/whiskey-mafia-leo-s-family-pc-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/whiskey-mafia-leo-s-family-pc-giveaway"
  },
  {
    "id": 3096,
    "title": "Madness Inside (itch.io) Giveaway",
    "worth": "$6.99",
    "thumbnail": "https://www.gamerpower.com/offers/1/67c76007697b3.jpg",
    "image": "https://www.gamerpower.com/offers/1b/67c76007697b3.jpg",
    "description": "Download Madness Inside for free on Itch.io! Madness Inside is an indie psychological walking simulator where you explore a psychiatric hospital.",
    "instructions": "1. Click the \"Get Giveaway\" button to visit the giveaway page.\r\n2. Click the button \"Download or Claim\" before the offer expires.\r\n3. Login into your itch.io account to access the game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/madness-inside-itch-io-giveaway",
    "published_date": "2026-07-02 09:03:43",
    "type": "Game",
    "platforms": "PC, Itch.io, DRM-Free",
    "end_date": "2026-08-01 23:59:59",
    "users": 118430,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/madness-inside-itch-io-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/madness-inside-itch-io-giveaway"
  },
  {
    "id": 3697,
    "title": "NIGHTBELL (Itch.io) Giveaway",
    "worth": "$3.99",
    "thumbnail": "https://www.gamerpower.com/offers/1/6a456f543d3c9.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6a456f543d3c9.jpg",
    "description": "Download NIGHTBELL for free on Itch.io until July 12th 2026. NIGHTBELL is a 3d first person game with a creepy atmosphere. Check it out.",
    "instructions": "1. Click the \"Get Giveaway\" button to visit the giveaway page.\r\n2. Click the button \"Download or Claim\" before the offer expires.\r\n3. Login into your itch.io account to access the game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/nightbell-itch-io-giveaway",
    "published_date": "2026-07-01 15:49:40",
    "type": "Game",
    "platforms": "PC, Itch.io, DRM-Free",
    "end_date": "2026-07-12 23:59:00",
    "users": 48850,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/nightbell-itch-io-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/nightbell-itch-io-giveaway"
  },
  {
    "id": 3676,
    "title": "Dire Echo (itchio) Giveaway",
    "worth": "$5.99",
    "thumbnail": "https://www.gamerpower.com/offers/1/6a27eafa35794.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6a27eafa35794.jpg",
    "description": "Explore deep space with this giveaway. Get Dire Echo for free on itch.io, a 3d sci-fi first-person exploration game featuring impressive visuals.",
    "instructions": "1. Click the \"Get Giveaway\" button to visit the giveaway page.\r\n2. Click the button \"Download or Claim\" before the offer expires.\r\n3. Login into your itch.io account to access the game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/dire-echo-itchio-giveaway",
    "published_date": "2026-07-01 14:53:19",
    "type": "Game",
    "platforms": "PC, Itch.io, DRM-Free",
    "end_date": "2026-07-12 23:59:00",
    "users": 57730,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/dire-echo-itchio-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/dire-echo-itchio-giveaway"
  },
  {
    "id": 3696,
    "title": "World of Warships Alienware Flag Pack Key Giveaway",
    "worth": "N/A",
    "thumbnail": "https://www.gamerpower.com/offers/1/6a45426a58fee.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6a45426a58fee.jpg",
    "description": "Redeem your Alienware Flag key in World of Warships and set sail in style.",
    "instructions": "1. Click the button to visit the giveaway page.\r\n2. Log in to your free Alienware Arena account and click the button to unlock your key.\r\n3. Follow the giveaway instructions to redeem your key.",
    "open_giveaway_url": "https://www.gamerpower.com/open/world-of-warships-alienware-flag-pack-key-giveaway",
    "published_date": "2026-07-01 12:38:02",
    "type": "DLC",
    "platforms": "PC",
    "end_date": "2026-09-06 23:59:00",
    "users": 4630,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/world-of-warships-alienware-flag-pack-key-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/world-of-warships-alienware-flag-pack-key-giveaway"
  },
  {
    "id": 3691,
    "title": "Crystal Saga Nova: Free Gift Pack Keys",
    "worth": "N/A",
    "thumbnail": "https://www.gamerpower.com/offers/1/6a3ab4213e0cd.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6a3ab4213e0cd.jpg",
    "description": "Claim your free Crystal Saga Nova Gift Pack key and unlock free in-game items including Dragon Coins and more!",
    "instructions": "1. Click the button to visit the giveaway page.\r\n2. Log in to your free MMOBomb account and click the button to unlock your key.\r\n3. Follow the giveaway instructions to redeem your key.",
    "open_giveaway_url": "https://www.gamerpower.com/open/crystal-saga-nova-free-gift-pack-keys",
    "published_date": "2026-06-23 12:28:17",
    "type": "DLC",
    "platforms": "PC",
    "end_date": "2028-01-01 23:59:00",
    "users": 9550,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/crystal-saga-nova-free-gift-pack-keys",
    "open_giveaway": "https://www.gamerpower.com/open/crystal-saga-nova-free-gift-pack-keys"
  },
  {
    "id": 3686,
    "title": "Mongil: Star Dive Gift Pack Key Giveaway",
    "worth": "N/A",
    "thumbnail": "https://www.gamerpower.com/offers/1/6a30710ca9c7d.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6a30710ca9c7d.jpg",
    "description": "Claim your free Mongil: Star Dive Gift Pack Key and unlock 50,000 In-Game Gold and Cappy Mama 2 Monsterling.",
    "instructions": "1. Click the button to visit the giveaway page.\r\n2. Register or log in to your AMD Gaming account and click the button to unlock your key.\r\n3. Follow the giveaway instructions to redeem your key.",
    "open_giveaway_url": "https://www.gamerpower.com/open/mongil-star-dive-gift-pack-key-giveaway",
    "published_date": "2026-06-15 17:39:24",
    "type": "DLC",
    "platforms": "PC, Android, iOS",
    "end_date": "N/A",
    "users": 13370,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/mongil-star-dive-gift-pack-key-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/mongil-star-dive-gift-pack-key-giveaway"
  },
  {
    "id": 3548,
    "title": "Static Voice (Itch.io) Giveaway",
    "worth": "$2.99",
    "thumbnail": "https://www.gamerpower.com/offers/1/69c5a81a64b29.jpg",
    "image": "https://www.gamerpower.com/offers/1b/69c5a81a64b29.jpg",
    "description": "Claim Static Voice for free on Itch.io! Static Voice is a first-person survival game where you play as a resident of an old Soviet apartment block.",
    "instructions": "1. Click the button to visit the giveaway page.\r\n2. Click the button \"Download or Claim\" before the offer expires.\r\n3. Login into your itch.io account to access the game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/static-voice-itch-io-giveaway",
    "published_date": "2026-06-10 20:27:18",
    "type": "Game",
    "platforms": "PC, Itch.io, DRM-Free",
    "end_date": "2026-07-11 23:59:31",
    "users": 61010,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/static-voice-itch-io-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/static-voice-itch-io-giveaway"
  },
  {
    "id": 3279,
    "title": "Blacklist Mafia (IndieGala) Giveaway",
    "worth": "$9.99",
    "thumbnail": "https://www.gamerpower.com/offers/1/68ca9583aca60.jpg",
    "image": "https://www.gamerpower.com/offers/1b/68ca9583aca60.jpg",
    "description": "Live your mafia fantasy! Grab Blacklist Mafia for free on IndieGala. Blacklist Mafia is a small 2D adventure game where you experience life in the mafia.",
    "instructions": "1. Click the button to visit the giveaway page.\r\n2. Login into your free IndieGala account.\r\n3. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n4. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/blacklist-mafia-pc-giveaway",
    "published_date": "2026-06-09 04:00:45",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 86270,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/blacklist-mafia-pc-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/blacklist-mafia-pc-giveaway"
  },
  {
    "id": 3675,
    "title": "Neverwinter: Cape of the Noble North Key Giveaway",
    "worth": "N/A",
    "thumbnail": "https://www.gamerpower.com/offers/1/6a2717e22a61f.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6a2717e22a61f.jpg",
    "description": "Claim your free Neverwinter Cape of the Noble North key, unlock this cosmetic item, and explore Neverwinter in style.",
    "instructions": "1. Click the button to visit the giveaway page.\r\n2. Log in to your free Alienware Arena account and click the button to unlock your key.\r\n3. Follow the giveaway instructions to redeem your key.",
    "open_giveaway_url": "https://www.gamerpower.com/open/neverwinter-cape-of-the-noble-north-key-giveaway",
    "published_date": "2026-06-08 15:28:34",
    "type": "DLC",
    "platforms": "PC",
    "end_date": "N/A",
    "users": 15630,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/neverwinter-cape-of-the-noble-north-key-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/neverwinter-cape-of-the-noble-north-key-giveaway"
  },
  {
    "id": 3656,
    "title": "007 First Light: Ops Radiant Outfit Key Giveaway",
    "worth": "N/A",
    "thumbnail": "https://www.gamerpower.com/offers/1/6a171b5b30add.jpg",
    "image": "https://www.gamerpower.com/offers/1b/6a171b5b30add.jpg",
    "description": "Redeem the 007 First Light: Ops Radiant Outfit Key to unlock the Ops Radiant outfit for 007. Please note this giveaway requires 5 ARP (Alienware Rewards Points) to claim a key. Fortunately, you can earn ARP daily for free.",
    "instructions": "1. Click the button to visit the giveaway page.\r\n2. Log in to your free Alienware Arena account and click the button to unlock your key.\r\n3. Follow the giveaway instructions to redeem your key.",
    "open_giveaway_url": "https://www.gamerpower.com/open/007-first-light-ops-radiant-outfit-key-giveaway",
    "published_date": "2026-05-27 12:27:07",
    "type": "DLC",
    "platforms": "PC, Playstation 5, Xbox Series X|S, Nintendo Switch",
    "end_date": "2027-05-27 23:59:00",
    "users": 19890,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/007-first-light-ops-radiant-outfit-key-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/007-first-light-ops-radiant-outfit-key-giveaway"
  },
  {
    "id": 3287,
    "title": "Mr.Brocco And Co (IndieGala) Giveaway",
    "worth": "$9.99",
    "thumbnail": "https://www.gamerpower.com/offers/1/68ce9db7d6736.jpg",
    "image": "https://www.gamerpower.com/offers/1b/68ce9db7d6736.jpg",
    "description": "Your fight against fast food begins today! Download Mr.Brocco And Co for free via IndieGala. Mr.Brocco And Co is a 2D platform game where junk food is trying to take over!",
    "instructions": "1. Click the button to visit the giveaway page.\r\n2. Login into your free IndieGala account.\r\n3. Scroll down and click the \"Add to Your Library\" button to add the game to your library.\r\n4. Go to \"My Library\" to find your game.",
    "open_giveaway_url": "https://www.gamerpower.com/open/mr-brocco-and-co-pc-giveaway",
    "published_date": "2026-05-23 08:11:19",
    "type": "Game",
    "platforms": "PC, DRM-Free",
    "end_date": "N/A",
    "users": 93020,
    "status": "Active",
    "gamerpower_url": "https://www.gamerpower.com/mr-brocco-and-co-pc-giveaway",
    "open_giveaway": "https://www.gamerpower.com/open/mr-brocco-and-co-pc-giveaway"
  }
]