export const categories= [
    {
      "id": "cat_action_adventure",
      "name": "Action & Adventure",
      "slug": "action-adventure",
      "description": "Fast-paced gameplay, exploration, and thrilling combat experiences.",
      "games": [
        {"id": "g_271590", "steam_app_id": 271590, "title": "Grand Theft Auto V", "developer": "Rockstar North", "publisher": "Rockstar Games", "release_date": "2015-04-14", "price_usd": 29.99, "rating": 90, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Open World", "Action", "Multiplayer"], "short_description": "Experience the sprawling world of Los Santos in this massive open-world action game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg", "store_link": "https://store.steampowered.com/app/271590/"},
        {"id": "g_1174180", "steam_app_id": 1174180, "title": "Red Dead Redemption 2", "developer": "Rockstar Games", "publisher": "Rockstar Games", "release_date": "2019-11-05", "price_usd": 59.99, "rating": 94, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Western", "Open World", "Story Rich"], "short_description": "America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg", "store_link": "https://store.steampowered.com/app/1174180/"},
        {"id": "g_292030", "steam_app_id": 292030, "title": "The Witcher 3: Wild Hunt", "developer": "CD PROJEKT RED", "publisher": "CD PROJEKT RED", "release_date": "2015-05-18", "price_usd": 39.99, "rating": 98, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["RPG", "Open World", "Fantasy"], "short_description": "Play as a highly trained monster slayer for hire in this massive, story-driven RPG.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg", "store_link": "https://store.steampowered.com/app/292030/"},
        {"id": "g_1091500", "steam_app_id": 1091500, "title": "Cyberpunk 2077", "developer": "CD PROJEKT RED", "publisher": "CD PROJEKT RED", "release_date": "2020-12-10", "price_usd": 59.99, "rating": 92, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Cyberpunk", "RPG", "Open World"], "short_description": "Become V, a cyberpunk mercenary in Night City, a megalopolis obsessed with power.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg", "store_link": "https://store.steampowered.com/app/1091500/"},
        {"id": "g_1245620", "steam_app_id": 1245620, "title": "Elden Ring", "developer": "FromSoftware", "publisher": "Bandai Namco", "release_date": "2022-02-25", "price_usd": 59.99, "rating": 96, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Souls-like", "Open World", "Dark Fantasy"], "short_description": "A sprawling action RPG set in the Lands Between, created by Miyazaki and Martin.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg", "store_link": "https://store.steampowered.com/app/1245620/"},
        {"id": "g_1593500", "steam_app_id": 1593500, "title": "God of War", "developer": "Santa Monica Studio", "publisher": "PlayStation PC LLC", "release_date": "2022-01-14", "price_usd": 49.99, "rating": 97, "platforms": ["Windows", "PlayStation"], "tags": ["Hack and Slash", "Mythology", "Story Rich"], "short_description": "Kratos must adapt to an unfamiliar world as he fights to save his son.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/header.jpg", "store_link": "https://store.steampowered.com/app/1593500/"},
        {"id": "g_814380", "steam_app_id": 814380, "title": "Sekiro: Shadows Die Twice", "developer": "FromSoftware", "publisher": "Activision", "release_date": "2019-03-22", "price_usd": 59.99, "rating": 95, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Souls-like", "Action", "Stealth"], "short_description": "Carve your own clever path to vengeance in an all-new adventure from FromSoftware.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/814380/header.jpg", "store_link": "https://store.steampowered.com/app/814380/"},
        {"id": "g_1172620", "steam_app_id": 1172620, "title": "Sea of Thieves", "developer": "Rare", "publisher": "Xbox Game Studios", "release_date": "2020-06-03", "price_usd": 39.99, "rating": 88, "platforms": ["Windows", "Xbox"], "tags": ["Pirates", "Open World", "Co-op"], "short_description": "A shared-world adventure game that lets you sail the seas as a pirate.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1172620/header.jpg", "store_link": "https://store.steampowered.com/app/1172620/"},
        {"id": "g_648800", "steam_app_id": 648800, "title": "Raft", "developer": "Redbeet Interactive", "publisher": "Axolot Games", "release_date": "2022-06-20", "price_usd": 19.99, "rating": 93, "platforms": ["Windows"], "tags": ["Survival", "Co-op", "Ocean"], "short_description": "Survive on a raft in an endless ocean, gathering debris and fighting off sharks.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/648800/header.jpg", "store_link": "https://store.steampowered.com/app/648800/"},
        {"id": "g_1085660", "steam_app_id": 1085660, "title": "Destiny 2", "developer": "Bungie", "publisher": "Bungie", "release_date": "2019-10-01", "price_usd": 0.00, "rating": 85, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["FPS", "Looter Shooter", "Free to Play"], "short_description": "A free-to-play action MMO with a shared world and seamless matchmaking.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1085660/header.jpg", "store_link": "https://store.steampowered.com/app/1085660/"}
      ]
    },
    {
      "id": "cat_puzzle_logic",
      "name": "Puzzle & Logic",
      "slug": "puzzle-logic",
      "description": "Mind-bending challenges, brain teasers, and clever problem-solving.",
      "games": [
        {"id": "g_105600", "steam_app_id": 105600, "title": "Portal 2", "developer": "Valve", "publisher": "Valve", "release_date": "2011-04-19", "price_usd": 9.99, "rating": 99, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox"], "tags": ["Puzzle", "FPS", "Story Rich"], "short_description": "The 'Perpetual Testing Initiative' has been expanded to allow you to design co-op puzzles!", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/105600/header.jpg", "store_link": "https://store.steampowered.com/app/105600/"},
        {"id": "g_620", "steam_app_id": 620, "title": "Portal", "developer": "Valve", "publisher": "Valve", "release_date": "2007-10-10", "price_usd": 9.99, "rating": 99, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["Puzzle", "FPS", "Sci-Fi"], "short_description": "A pioneering first-person puzzle game that redefined the genre.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg", "store_link": "https://store.steampowered.com/app/620/"},
        {"id": "g_220", "steam_app_id": 220, "title": "Half-Life 2", "developer": "Valve", "publisher": "Valve", "release_date": "2004-11-16", "price_usd": 9.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux"], "tags": ["FPS", "Story Rich", "Classic"], "short_description": "The sequel to the groundbreaking Half-Life, featuring revolutionary physics and storytelling.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/220/header.jpg", "store_link": "https://store.steampowered.com/app/220/"},
        {"id": "g_20920", "steam_app_id": 20920, "title": "The Witcher: Enhanced Edition", "developer": "CD PROJEKT RED", "publisher": "CD PROJEKT RED", "release_date": "2008-09-16", "price_usd": 9.99, "rating": 90, "platforms": ["Windows", "macOS"], "tags": ["RPG", "Fantasy", "Story Rich"], "short_description": "The original Witcher game that started it all, now enhanced with new content.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/20920/header.jpg", "store_link": "https://store.steampowered.com/app/20920/"}
      ]
    },
    {
      "id": "cat_platformer",
      "name": "Platformer",
      "slug": "platformer",
      "description": "Jump, run, and navigate through challenging levels with precision timing.",
      "games": [
        {"id": "g_367520", "steam_app_id": 367520, "title": "Hollow Knight", "developer": "Team Cherry", "publisher": "Team Cherry", "release_date": "2017-02-24", "price_usd": 14.99, "rating": 99, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["Metroidvania", "Souls-like", "Indie"], "short_description": "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg", "store_link": "https://store.steampowered.com/app/367520/"},
        {"id": "g_108600", "steam_app_id": 108600, "title": "Terraria", "developer": "Re-Logic", "publisher": "Re-Logic", "release_date": "2011-05-16", "price_usd": 9.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch", "Mobile"], "tags": ["Sandbox", "Survival", "2D"], "short_description": "Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/108600/header.jpg", "store_link": "https://store.steampowered.com/app/108600/"},
        {"id": "g_413150", "steam_app_id": 413150, "title": "Stardew Valley", "developer": "ConcernedApe", "publisher": "ConcernedApe", "release_date": "2016-02-26", "price_usd": 14.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch", "Mobile"], "tags": ["Farming Sim", "Relaxing", "Pixel Graphics"], "short_description": "Move to the countryside, cultivate a new life, and restore the old farm.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg", "store_link": "https://store.steampowered.com/app/413150/"},
        {"id": "g_268910", "steam_app_id": 268910, "title": "Cuphead", "developer": "Studio MDHR Entertainment Inc.", "publisher": "Studio MDHR Entertainment Inc.", "release_date": "2017-09-29", "price_usd": 19.99, "rating": 96, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["Action", "Difficult", "Co-op"], "short_description": "A classic run and gun action game heavily focused on boss battles.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/268910/header.jpg", "store_link": "https://store.steampowered.com/app/268910/"}
      ]
    },
    {
      "id": "cat_fighting",
      "name": "Fighting",
      "slug": "fighting",
      "description": "One-on-one combat, combos, and competitive multiplayer battles.",
      "games": [
        {"id": "g_311210", "steam_app_id": 311210, "title": "Mortal Kombat 11", "developer": "NetherRealm Studios", "publisher": "Warner Bros. Interactive Entertainment", "release_date": "2019-05-22", "price_usd": 39.99, "rating": 91, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["Fighting", "Violent", "Gore"], "short_description": "Mortal Kombat is back and better than ever in the next evolution of the iconic franchise.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/311210/header.jpg", "store_link": "https://store.steampowered.com/app/311210/"},
        {"id": "g_534380", "steam_app_id": 534380, "title": "Dragon Ball FighterZ", "developer": "ARC SYSTEM WORKS", "publisher": "Bandai Namco Entertainment", "release_date": "2018-01-26", "price_usd": 39.99, "rating": 93, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["Fighting", "Anime", "2D Fighter"], "short_description": "Dragon Ball FighterZ is born to provide a definitive Dragon Ball gaming experience.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/534380/header.jpg", "store_link": "https://store.steampowered.com/app/534380/"},
        {"id": "g_237870", "steam_app_id": 237870, "title": "Ultimate Marvel vs. Capcom 3", "developer": "CAPCOM", "publisher": "CAPCOM", "release_date": "2012-11-15", "price_usd": 24.99, "rating": 92, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Fighting", "2D Fighter", "Action"], "short_description": "The definitive version of the legendary crossover fighting game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/237870/header.jpg", "store_link": "https://store.steampowered.com/app/237870/"},
        {"id": "g_384000", "steam_app_id": 384000, "title": "Street Fighter V", "developer": "CAPCOM", "publisher": "CAPCOM", "release_date": "2016-02-16", "price_usd": 19.99, "rating": 85, "platforms": ["Windows", "PlayStation"], "tags": ["Fighting", "2D Fighter", "Competitive"], "short_description": "The legendary fighting franchise returns with Street Fighter V.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/384000/header.jpg", "store_link": "https://store.steampowered.com/app/384000/"}
      ]
    },
    {
      "id": "cat_sports",
      "name": "Sports",
      "slug": "sports",
      "description": "Realistic sports simulations, arcade sports, and athletic competitions.",
      "games": [
        {"id": "g_1551360", "steam_app_id": 1551360, "title": "Forza Horizon 5", "developer": "Playground Games", "publisher": "Xbox Game Studios", "release_date": "2021-11-09", "price_usd": 59.99, "rating": 94, "platforms": ["Windows", "Xbox"], "tags": ["Racing", "Open World", "Cars"], "short_description": "Your ultimate Horizon adventure awaits! Explore the vibrant landscapes of Mexico.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg", "store_link": "https://store.steampowered.com/app/1551360/"},
        {"id": "g_1250410", "steam_app_id": 1250410, "title": "Microsoft Flight Simulator", "developer": "Asobo Studio", "publisher": "Xbox Game Studios", "release_date": "2021-07-27", "price_usd": 59.99, "rating": 92, "platforms": ["Windows", "Xbox"], "tags": ["Flight Sim", "Realistic", "Exploration"], "short_description": "Explore the world with unprecedented realism in this next-gen flight simulator.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1250410/header.jpg", "store_link": "https://store.steampowered.com/app/1250410/"},
        {"id": "g_227300", "steam_app_id": 227300, "title": "Euro Truck Simulator 2", "developer": "SCS Software", "publisher": "SCS Software", "release_date": "2012-10-19", "price_usd": 19.99, "rating": 97, "platforms": ["Windows", "macOS", "Linux"], "tags": ["Driving", "Relaxing", "Moddable"], "short_description": "Travel across Europe as king of the road, a trucker hauling impressive cargo.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/227300/header.jpg", "store_link": "https://store.steampowered.com/app/227300/"},
        {"id": "g_236390", "steam_app_id": 236390, "title": "War Thunder", "developer": "Gaijin Entertainment", "publisher": "Gaijin Entertainment", "release_date": "2013-08-15", "price_usd": 0.00, "rating": 78, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox"], "tags": ["Vehicular Combat", "Flight Sim", "Free to Play"], "short_description": "The most comprehensive free-to-play military game featuring aviation, armor, and fleets.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/236390/header.jpg", "store_link": "https://store.steampowered.com/app/236390/"}
      ]
    },
    {
      "id": "cat_music_rhythm",
      "name": "Music & Rhythm",
      "slug": "music-rhythm",
      "description": "Dance to the beat, play instruments, and experience music like never before.",
      "games": [
        {"id": "g_620930", "steam_app_id": 620930, "title": "Beat Saber", "developer": "Beat Games", "publisher": "Beat Games", "release_date": "2019-05-21", "price_usd": 29.99, "rating": 95, "platforms": ["Windows", "VR"], "tags": ["VR", "Rhythm", "Music"], "short_description": "Slash beats to an adrenaline-pumping playlist of music created by the community.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/620930/header.jpg", "store_link": "https://store.steampowered.com/app/620930/"},
        {"id": "g_244820", "steam_app_id": 244820, "title": "SpaceChem", "developer": "Zachtronics", "publisher": "Zachtronics", "release_date": "2011-03-02", "price_usd": 9.99, "rating": 94, "platforms": ["Windows", "macOS", "Linux"], "tags": ["Puzzle", "Programming", "Difficult"], "short_description": "Zachtronics is back with an ambitious new design-based puzzle game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/244820/header.jpg", "store_link": "https://store.steampowered.com/app/244820/"},
        {"id": "g_275850", "steam_app_id": 275850, "title": "No Man's Sky", "developer": "Hello Games", "publisher": "Hello Games", "release_date": "2016-08-12", "price_usd": 59.99, "rating": 90, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["Space", "Exploration", "Survival"], "short_description": "Explore an infinite universe of unique planets and lifeforms.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/275850/header.jpg", "store_link": "https://store.steampowered.com/app/275850/"},
        {"id": "g_108600", "steam_app_id": 108600, "title": "Terraria", "developer": "Re-Logic", "publisher": "Re-Logic", "release_date": "2011-05-16", "price_usd": 9.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch", "Mobile"], "tags": ["Sandbox", "Survival", "2D"], "short_description": "Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/108600/header.jpg", "store_link": "https://store.steampowered.com/app/108600/"}
      ]
    },
    {
      "id": "cat_card_board",
      "name": "Card & Board Games",
      "slug": "card-board",
      "description": "Strategic card games, classic board games, and tabletop experiences.",
      "games": [
        {"id": "g_291480", "steam_app_id": 291480, "title": "RimWorld", "developer": "Ludeon Studios", "publisher": "Ludeon Studios", "release_date": "2018-10-17", "price_usd": 34.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux"], "tags": ["Colony Sim", "Sci-Fi", "Story Generator"], "short_description": "A sci-fi colony sim driven by an intelligent AI storyteller.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/291480/header.jpg", "store_link": "https://store.steampowered.com/app/291480/"},
        {"id": "g_427520", "steam_app_id": 427520, "title": "Factorio", "developer": "Wube Software LTD.", "publisher": "Wube Software LTD.", "release_date": "2020-08-14", "price_usd": 35.00, "rating": 99, "platforms": ["Windows", "macOS", "Linux", "Switch"], "tags": ["Automation", "Base Building", "Management"], "short_description": "Build and maintain factories in an alien world, automate production.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/427520/header.jpg", "store_link": "https://store.steampowered.com/app/427520/"},
        {"id": "g_289070", "steam_app_id": 289070, "title": "Sid Meier's Civilization VI", "developer": "Firaxis Games", "publisher": "2K", "release_date": "2016-10-21", "price_usd": 59.99, "rating": 94, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["4X", "Turn-Based Strategy", "Historical"], "short_description": "Build an empire to stand the test of time in this award-winning strategy masterpiece.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/289070/header.jpg", "store_link": "https://store.steampowered.com/app/289070/"},
        {"id": "g_504230", "steam_app_id": 504230, "title": "Slay the Spire", "developer": "MegaCrit", "publisher": "MegaCrit", "release_date": "2019-01-23", "price_usd": 24.99, "rating": 97, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["Roguelike", "Card Game", "Strategy"], "short_description": "We fused card games and roguelikes together to make the best single player deckbuilder we could.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/504230/header.jpg", "store_link": "https://store.steampowered.com/app/504230/"}
      ]
    },
    {
      "id": "cat_visual_novel",
      "name": "Visual Novel",
      "slug": "visual-novel",
      "description": "Story-driven experiences with beautiful art, branching narratives, and character development.",
      "games": [
        {"id": "g_1687950", "steam_app_id": 1687950, "title": "Persona 5 Royal", "developer": "ATLUS", "publisher": "SEGA", "release_date": "2022-10-21", "price_usd": 39.99, "rating": 97, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["JRPG", "Anime", "Turn-Based"], "short_description": "Don a mask and join the Phantom Thieves of Hearts to reform the corrupt.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1687950/header.jpg", "store_link": "https://store.steampowered.com/app/1687950/"},
        {"id": "g_427520", "steam_app_id": 427520, "title": "Factorio", "developer": "Wube Software LTD.", "publisher": "Wube Software LTD.", "release_date": "2020-08-14", "price_usd": 35.00, "rating": 99, "platforms": ["Windows", "macOS", "Linux", "Switch"], "tags": ["Automation", "Base Building", "Management"], "short_description": "Build and maintain factories in an alien world, automate production.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/427520/header.jpg", "store_link": "https://store.steampowered.com/app/427520/"},
        {"id": "g_291480", "steam_app_id": 291480, "title": "RimWorld", "developer": "Ludeon Studios", "publisher": "Ludeon Studios", "release_date": "2018-10-17", "price_usd": 34.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux"], "tags": ["Colony Sim", "Sci-Fi", "Story Generator"], "short_description": "A sci-fi colony sim driven by an intelligent AI storyteller.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/291480/header.jpg", "store_link": "https://store.steampowered.com/app/291480/"},
        {"id": "g_1086940", "steam_app_id": 1086940, "title": "Baldur's Gate 3", "developer": "Larian Studios", "publisher": "Larian Studios", "release_date": "2023-08-03", "price_usd": 59.99, "rating": 98, "platforms": ["Windows", "macOS", "PlayStation"], "tags": ["D&D", "Turn-Based", "Co-op"], "short_description": "Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg", "store_link": "https://store.steampowered.com/app/1086940/"}
      ]
    },
    {
      "id": "cat_stealth",
      "name": "Stealth",
      "slug": "stealth",
      "description": "Sneak past enemies, avoid detection, and complete missions undetected.",
      "games": [
        {"id": "g_814380", "steam_app_id": 814380, "title": "Sekiro: Shadows Die Twice", "developer": "FromSoftware", "publisher": "Activision", "release_date": "2019-03-22", "price_usd": 59.99, "rating": 95, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Souls-like", "Action", "Stealth"], "short_description": "Carve your own clever path to vengeance in an all-new adventure from FromSoftware.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/814380/header.jpg", "store_link": "https://store.steampowered.com/app/814380/"},
        {"id": "g_1144200", "steam_app_id": 1144200, "title": "Ready or Not", "developer": "VOID Interactive", "publisher": "VOID Interactive", "release_date": "2023-12-13", "price_usd": 49.99, "rating": 93, "platforms": ["Windows"], "tags": ["Tactical", "FPS", "Realistic"], "short_description": "A tactical first-person shooter that simulates real-world police operations.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1144200/header.jpg", "store_link": "https://store.steampowered.com/app/1144200/"},
        {"id": "g_359550", "steam_app_id": 359550, "title": "Tom Clancy's Rainbow Six Siege", "developer": "Ubisoft Montreal", "publisher": "Ubisoft", "release_date": "2015-12-01", "price_usd": 19.99, "rating": 87, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Tactical", "FPS", "Destruction"], "short_description": "Master the art of destruction as you lead your team in intense close-quarters combat.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/359550/header.jpg", "store_link": "https://store.steampowered.com/app/359550/"},
        {"id": "g_271590", "steam_app_id": 271590, "title": "Grand Theft Auto V", "developer": "Rockstar North", "publisher": "Rockstar Games", "release_date": "2015-04-14", "price_usd": 29.99, "rating": 90, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Open World", "Action", "Multiplayer"], "short_description": "Experience the sprawling world of Los Santos in this massive open-world action game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg", "store_link": "https://store.steampowered.com/app/271590/"}
      ]
    },
    {
      "id": "cat_open_world",
      "name": "Open World",
      "slug": "open-world",
      "description": "Vast, explorable worlds with freedom to roam and discover at your own pace.",
      "games": [
        {"id": "g_271590", "steam_app_id": 271590, "title": "Grand Theft Auto V", "developer": "Rockstar North", "publisher": "Rockstar Games", "release_date": "2015-04-14", "price_usd": 29.99, "rating": 90, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Open World", "Action", "Multiplayer"], "short_description": "Experience the sprawling world of Los Santos in this massive open-world action game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg", "store_link": "https://store.steampowered.com/app/271590/"},
        {"id": "g_1174180", "steam_app_id": 1174180, "title": "Red Dead Redemption 2", "developer": "Rockstar Games", "publisher": "Rockstar Games", "release_date": "2019-11-05", "price_usd": 59.99, "rating": 94, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Western", "Open World", "Story Rich"], "short_description": "America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg", "store_link": "https://store.steampowered.com/app/1174180/"},
        {"id": "g_292030", "steam_app_id": 292030, "title": "The Witcher 3: Wild Hunt", "developer": "CD PROJEKT RED", "publisher": "CD PROJEKT RED", "release_date": "2015-05-18", "price_usd": 39.99, "rating": 98, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["RPG", "Open World", "Fantasy"], "short_description": "Play as a highly trained monster slayer for hire in this massive, story-driven RPG.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg", "store_link": "https://store.steampowered.com/app/292030/"},
        {"id": "g_1245620", "steam_app_id": 1245620, "title": "Elden Ring", "developer": "FromSoftware", "publisher": "Bandai Namco", "release_date": "2022-02-25", "price_usd": 59.99, "rating": 96, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Souls-like", "Open World", "Dark Fantasy"], "short_description": "A sprawling action RPG set in the Lands Between, created by Miyazaki and Martin.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg", "store_link": "https://store.steampowered.com/app/1245620/"}
      ]
    },
    {
      "id": "cat_sandbox",
      "name": "Sandbox",
      "slug": "sandbox",
      "description": "Creative freedom, building, and emergent gameplay with minimal restrictions.",
      "games": [
        {"id": "g_108600", "steam_app_id": 108600, "title": "Terraria", "developer": "Re-Logic", "publisher": "Re-Logic", "release_date": "2011-05-16", "price_usd": 9.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch", "Mobile"], "tags": ["Sandbox", "Survival", "2D"], "short_description": "Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/108600/header.jpg", "store_link": "https://store.steampowered.com/app/108600/"},
        {"id": "g_413150", "steam_app_id": 413150, "title": "Stardew Valley", "developer": "ConcernedApe", "publisher": "ConcernedApe", "release_date": "2016-02-26", "price_usd": 14.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch", "Mobile"], "tags": ["Farming Sim", "Relaxing", "Pixel Graphics"], "short_description": "Move to the countryside, cultivate a new life, and restore the old farm.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg", "store_link": "https://store.steampowered.com/app/413150/"},
        {"id": "g_252490", "steam_app_id": 252490, "title": "Rust", "developer": "Facepunch Studios", "publisher": "Facepunch Studios", "release_date": "2018-02-08", "price_usd": 39.99, "rating": 88, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox"], "tags": ["Survival", "Multiplayer", "PvP"], "short_description": "The only aim in Rust is to survive. Everything wants you to die.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg", "store_link": "https://store.steampowered.com/app/252490/"},
        {"id": "g_304930", "steam_app_id": 304930, "title": "Unturned", "developer": "Smartly Dressed Games", "publisher": "Smartly Dressed Games", "release_date": "2017-07-07", "price_usd": 0.00, "rating": 91, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["Survival", "Zombies", "Free to Play"], "short_description": "A free-to-play sandbox survival game with blocky graphics and deep mechanics.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/304930/header.jpg", "store_link": "https://store.steampowered.com/app/304930/"}
      ]
    },
    {
      "id": "cat_building_construction",
      "name": "Building & Construction",
      "slug": "building-construction",
      "description": "Design, build, and manage structures, cities, and complex systems.",
      "games": [
        {"id": "g_427520", "steam_app_id": 427520, "title": "Factorio", "developer": "Wube Software LTD.", "publisher": "Wube Software LTD.", "release_date": "2020-08-14", "price_usd": 35.00, "rating": 99, "platforms": ["Windows", "macOS", "Linux", "Switch"], "tags": ["Automation", "Base Building", "Management"], "short_description": "Build and maintain factories in an alien world, automate production.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/427520/header.jpg", "store_link": "https://store.steampowered.com/app/427520/"},
        {"id": "g_291480", "steam_app_id": 291480, "title": "RimWorld", "developer": "Ludeon Studios", "publisher": "Ludeon Studios", "release_date": "2018-10-17", "price_usd": 34.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux"], "tags": ["Colony Sim", "Sci-Fi", "Story Generator"], "short_description": "A sci-fi colony sim driven by an intelligent AI storyteller.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/291480/header.jpg", "store_link": "https://store.steampowered.com/app/291480/"},
        {"id": "g_251570", "steam_app_id": 251570, "title": "7 Days to Die", "developer": "The Fun Pimps", "publisher": "The Fun Pimps Entertainment LLC", "release_date": "2024-07-25", "price_usd": 44.99, "rating": 89, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Survival", "Zombies", "Crafting"], "short_description": "A brutal zombie survival game with deep crafting and building mechanics.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/251570/header.jpg", "store_link": "https://store.steampowered.com/app/251570/"},
        {"id": "g_108600", "steam_app_id": 108600, "title": "Terraria", "developer": "Re-Logic", "publisher": "Re-Logic", "release_date": "2011-05-16", "price_usd": 9.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch", "Mobile"], "tags": ["Sandbox", "Survival", "2D"], "short_description": "Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/108600/header.jpg", "store_link": "https://store.steampowered.com/app/108600/"}
      ]
    },
    {
      "id": "cat_farming_life_sim",
      "name": "Farming & Life Simulation",
      "slug": "farming-life-sim",
      "description": "Cultivate crops, raise animals, and build a peaceful life in rural settings.",
      "games": [
        {"id": "g_413150", "steam_app_id": 413150, "title": "Stardew Valley", "developer": "ConcernedApe", "publisher": "ConcernedApe", "release_date": "2016-02-26", "price_usd": 14.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch", "Mobile"], "tags": ["Farming Sim", "Relaxing", "Pixel Graphics"], "short_description": "Move to the countryside, cultivate a new life, and restore the old farm.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg", "store_link": "https://store.steampowered.com/app/413150/"},
        {"id": "g_291480", "steam_app_id": 291480, "title": "RimWorld", "developer": "Ludeon Studios", "publisher": "Ludeon Studios", "release_date": "2018-10-17", "price_usd": 34.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux"], "tags": ["Colony Sim", "Sci-Fi", "Story Generator"], "short_description": "A sci-fi colony sim driven by an intelligent AI storyteller.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/291480/header.jpg", "store_link": "https://store.steampowered.com/app/291480/"},
        {"id": "g_108600", "steam_app_id": 108600, "title": "Terraria", "developer": "Re-Logic", "publisher": "Re-Logic", "release_date": "2011-05-16", "price_usd": 9.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch", "Mobile"], "tags": ["Sandbox", "Survival", "2D"], "short_description": "Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/108600/header.jpg", "store_link": "https://store.steampowered.com/app/108600/"},
        {"id": "g_227300", "steam_app_id": 227300, "title": "Euro Truck Simulator 2", "developer": "SCS Software", "publisher": "SCS Software", "release_date": "2012-10-19", "price_usd": 19.99, "rating": 97, "platforms": ["Windows", "macOS", "Linux"], "tags": ["Driving", "Relaxing", "Moddable"], "short_description": "Travel across Europe as king of the road, a trucker hauling impressive cargo.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/227300/header.jpg", "store_link": "https://store.steampowered.com/app/227300/"}
      ]
    },
    {
      "id": "cat_city_builder",
      "name": "City Builder",
      "slug": "city-builder",
      "description": "Plan and manage entire cities, from infrastructure to citizen happiness.",
      "games": [
        {"id": "g_289070", "steam_app_id": 289070, "title": "Sid Meier's Civilization VI", "developer": "Firaxis Games", "publisher": "2K", "release_date": "2016-10-21", "price_usd": 59.99, "rating": 94, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["4X", "Turn-Based Strategy", "Historical"], "short_description": "Build an empire to stand the test of time in this award-winning strategy masterpiece.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/289070/header.jpg", "store_link": "https://store.steampowered.com/app/289070/"},
        {"id": "g_427520", "steam_app_id": 427520, "title": "Factorio", "developer": "Wube Software LTD.", "publisher": "Wube Software LTD.", "release_date": "2020-08-14", "price_usd": 35.00, "rating": 99, "platforms": ["Windows", "macOS", "Linux", "Switch"], "tags": ["Automation", "Base Building", "Management"], "short_description": "Build and maintain factories in an alien world, automate production.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/427520/header.jpg", "store_link": "https://store.steampowered.com/app/427520/"},
        {"id": "g_291480", "steam_app_id": 291480, "title": "RimWorld", "developer": "Ludeon Studios", "publisher": "Ludeon Studios", "release_date": "2018-10-17", "price_usd": 34.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux"], "tags": ["Colony Sim", "Sci-Fi", "Story Generator"], "short_description": "A sci-fi colony sim driven by an intelligent AI storyteller.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/291480/header.jpg", "store_link": "https://store.steampowered.com/app/291480/"},
        {"id": "g_251570", "steam_app_id": 251570, "title": "7 Days to Die", "developer": "The Fun Pimps", "publisher": "The Fun Pimps Entertainment LLC", "release_date": "2024-07-25", "price_usd": 44.99, "rating": 89, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Survival", "Zombies", "Crafting"], "short_description": "A brutal zombie survival game with deep crafting and building mechanics.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/251570/header.jpg", "store_link": "https://store.steampowered.com/app/251570/"}
      ]
    },
    {
      "id": "cat_management_business",
      "name": "Management & Business",
      "slug": "management-business",
      "description": "Run businesses, manage resources, and make strategic decisions for success.",
      "games": [
        {"id": "g_427520", "steam_app_id": 427520, "title": "Factorio", "developer": "Wube Software LTD.", "publisher": "Wube Software LTD.", "release_date": "2020-08-14", "price_usd": 35.00, "rating": 99, "platforms": ["Windows", "macOS", "Linux", "Switch"], "tags": ["Automation", "Base Building", "Management"], "short_description": "Build and maintain factories in an alien world, automate production.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/427520/header.jpg", "store_link": "https://store.steampowered.com/app/427520/"},
        {"id": "g_291480", "steam_app_id": 291480, "title": "RimWorld", "developer": "Ludeon Studios", "publisher": "Ludeon Studios", "release_date": "2018-10-17", "price_usd": 34.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux"], "tags": ["Colony Sim", "Sci-Fi", "Story Generator"], "short_description": "A sci-fi colony sim driven by an intelligent AI storyteller.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/291480/header.jpg", "store_link": "https://store.steampowered.com/app/291480/"},
        {"id": "g_289070", "steam_app_id": 289070, "title": "Sid Meier's Civilization VI", "developer": "Firaxis Games", "publisher": "2K", "release_date": "2016-10-21", "price_usd": 59.99, "rating": 94, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["4X", "Turn-Based Strategy", "Historical"], "short_description": "Build an empire to stand the test of time in this award-winning strategy masterpiece.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/289070/header.jpg", "store_link": "https://store.steampowered.com/app/289070/"},
        {"id": "g_227300", "steam_app_id": 227300, "title": "Euro Truck Simulator 2", "developer": "SCS Software", "publisher": "SCS Software", "release_date": "2012-10-19", "price_usd": 19.99, "rating": 97, "platforms": ["Windows", "macOS", "Linux"], "tags": ["Driving", "Relaxing", "Moddable"], "short_description": "Travel across Europe as king of the road, a trucker hauling impressive cargo.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/227300/header.jpg", "store_link": "https://store.steampowered.com/app/227300/"}
      ]
    },
    {
      "id": "cat_educational",
      "name": "Educational",
      "slug": "educational",
      "description": "Learn while you play with games designed to teach and inform.",
      "games": [
        {"id": "g_1250410", "steam_app_id": 1250410, "title": "Microsoft Flight Simulator", "developer": "Asobo Studio", "publisher": "Xbox Game Studios", "release_date": "2021-07-27", "price_usd": 59.99, "rating": 92, "platforms": ["Windows", "Xbox"], "tags": ["Flight Sim", "Realistic", "Exploration"], "short_description": "Explore the world with unprecedented realism in this next-gen flight simulator.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1250410/header.jpg", "store_link": "https://store.steampowered.com/app/1250410/"},
        {"id": "g_227300", "steam_app_id": 227300, "title": "Euro Truck Simulator 2", "developer": "SCS Software", "publisher": "SCS Software", "release_date": "2012-10-19", "price_usd": 19.99, "rating": 97, "platforms": ["Windows", "macOS", "Linux"], "tags": ["Driving", "Relaxing", "Moddable"], "short_description": "Travel across Europe as king of the road, a trucker hauling impressive cargo.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/227300/header.jpg", "store_link": "https://store.steampowered.com/app/227300/"},
        {"id": "g_289070", "steam_app_id": 289070, "title": "Sid Meier's Civilization VI", "developer": "Firaxis Games", "publisher": "2K", "release_date": "2016-10-21", "price_usd": 59.99, "rating": 94, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["4X", "Turn-Based Strategy", "Historical"], "short_description": "Build an empire to stand the test of time in this award-winning strategy masterpiece.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/289070/header.jpg", "store_link": "https://store.steampowered.com/app/289070/"},
        {"id": "g_236390", "steam_app_id": 236390, "title": "War Thunder", "developer": "Gaijin Entertainment", "publisher": "Gaijin Entertainment", "release_date": "2013-08-15", "price_usd": 0.00, "rating": 78, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox"], "tags": ["Vehicular Combat", "Flight Sim", "Free to Play"], "short_description": "The most comprehensive free-to-play military game featuring aviation, armor, and fleets.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/236390/header.jpg", "store_link": "https://store.steampowered.com/app/236390/"}
      ]
    },
    {
      "id": "cat_casual",
      "name": "Casual",
      "slug": "casual",
      "description": "Easy to pick up, relaxing gameplay perfect for unwinding.",
      "games": [
        {"id": "g_413150", "steam_app_id": 413150, "title": "Stardew Valley", "developer": "ConcernedApe", "publisher": "ConcernedApe", "release_date": "2016-02-26", "price_usd": 14.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch", "Mobile"], "tags": ["Farming Sim", "Relaxing", "Pixel Graphics"], "short_description": "Move to the countryside, cultivate a new life, and restore the old farm.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg", "store_link": "https://store.steampowered.com/app/413150/"},
        {"id": "g_227300", "steam_app_id": 227300, "title": "Euro Truck Simulator 2", "developer": "SCS Software", "publisher": "SCS Software", "release_date": "2012-10-19", "price_usd": 19.99, "rating": 97, "platforms": ["Windows", "macOS", "Linux"], "tags": ["Driving", "Relaxing", "Moddable"], "short_description": "Travel across Europe as king of the road, a trucker hauling impressive cargo.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/227300/header.jpg", "store_link": "https://store.steampowered.com/app/227300/"},
        {"id": "g_108600", "steam_app_id": 108600, "title": "Terraria", "developer": "Re-Logic", "publisher": "Re-Logic", "release_date": "2011-05-16", "price_usd": 9.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch", "Mobile"], "tags": ["Sandbox", "Survival", "2D"], "short_description": "Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/108600/header.jpg", "store_link": "https://store.steampowered.com/app/108600/"},
        {"id": "g_648800", "steam_app_id": 648800, "title": "Raft", "developer": "Redbeet Interactive", "publisher": "Axolot Games", "release_date": "2022-06-20", "price_usd": 19.99, "rating": 93, "platforms": ["Windows"], "tags": ["Survival", "Co-op", "Ocean"], "short_description": "Survive on a raft in an endless ocean, gathering debris and fighting off sharks.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/648800/header.jpg", "store_link": "https://store.steampowered.com/app/648800/"}
      ]
    },
    {
      "id": "cat_arcade",
      "name": "Arcade",
      "slug": "arcade",
      "description": "Fast-paced, score-based gameplay inspired by classic arcade games.",
      "games": [
        {"id": "g_268910", "steam_app_id": 268910, "title": "Cuphead", "developer": "Studio MDHR Entertainment Inc.", "publisher": "Studio MDHR Entertainment Inc.", "release_date": "2017-09-29", "price_usd": 19.99, "rating": 96, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["Action", "Difficult", "Co-op"], "short_description": "A classic run and gun action game heavily focused on boss battles.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/268910/header.jpg", "store_link": "https://store.steampowered.com/app/268910/"},
        {"id": "g_108600", "steam_app_id": 108600, "title": "Terraria", "developer": "Re-Logic", "publisher": "Re-Logic", "release_date": "2011-05-16", "price_usd": 9.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch", "Mobile"], "tags": ["Sandbox", "Survival", "2D"], "short_description": "Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/108600/header.jpg", "store_link": "https://store.steampowered.com/app/108600/"},
        {"id": "g_367520", "steam_app_id": 367520, "title": "Hollow Knight", "developer": "Team Cherry", "publisher": "Team Cherry", "release_date": "2017-02-24", "price_usd": 14.99, "rating": 99, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["Metroidvania", "Souls-like", "Indie"], "short_description": "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg", "store_link": "https://store.steampowered.com/app/367520/"},
        {"id": "g_620", "steam_app_id": 620, "title": "Portal", "developer": "Valve", "publisher": "Valve", "release_date": "2007-10-10", "price_usd": 9.99, "rating": 99, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["Puzzle", "FPS", "Sci-Fi"], "short_description": "A pioneering first-person puzzle game that redefined the genre.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg", "store_link": "https://store.steampowered.com/app/620/"}
      ]
    },
    {
      "id": "cat_retro_classic",
      "name": "Retro & Classic",
      "slug": "retro-classic",
      "description": "Nostalgic gameplay and pixel art inspired by gaming's golden age.",
      "games": [
        {"id": "g_413150", "steam_app_id": 413150, "title": "Stardew Valley", "developer": "ConcernedApe", "publisher": "ConcernedApe", "release_date": "2016-02-26", "price_usd": 14.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch", "Mobile"], "tags": ["Farming Sim", "Relaxing", "Pixel Graphics"], "short_description": "Move to the countryside, cultivate a new life, and restore the old farm.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg", "store_link": "https://store.steampowered.com/app/413150/"},
        {"id": "g_108600", "steam_app_id": 108600, "title": "Terraria", "developer": "Re-Logic", "publisher": "Re-Logic", "release_date": "2011-05-16", "price_usd": 9.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch", "Mobile"], "tags": ["Sandbox", "Survival", "2D"], "short_description": "Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/108600/header.jpg", "store_link": "https://store.steampowered.com/app/108600/"},
        {"id": "g_367520", "steam_app_id": 367520, "title": "Hollow Knight", "developer": "Team Cherry", "publisher": "Team Cherry", "release_date": "2017-02-24", "price_usd": 14.99, "rating": 99, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["Metroidvania", "Souls-like", "Indie"], "short_description": "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg", "store_link": "https://store.steampowered.com/app/367520/"},
        {"id": "g_620", "steam_app_id": 620, "title": "Portal", "developer": "Valve", "publisher": "Valve", "release_date": "2007-10-10", "price_usd": 9.99, "rating": 99, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["Puzzle", "FPS", "Sci-Fi"], "short_description": "A pioneering first-person puzzle game that redefined the genre.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg", "store_link": "https://store.steampowered.com/app/620/"}
      ]
    },
    {
      "id": "cat_vr_games",
      "name": "VR Games",
      "slug": "vr-games",
      "description": "Immersive virtual reality experiences that transport you to new worlds.",
      "games": [
        {"id": "g_620930", "steam_app_id": 620930, "title": "Beat Saber", "developer": "Beat Games", "publisher": "Beat Games", "release_date": "2019-05-21", "price_usd": 29.99, "rating": 95, "platforms": ["Windows", "VR"], "tags": ["VR", "Rhythm", "Music"], "short_description": "Slash beats to an adrenaline-pumping playlist of music created by the community.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/620930/header.jpg", "store_link": "https://store.steampowered.com/app/620930/"},
        {"id": "g_108600", "steam_app_id": 108600, "title": "Terraria", "developer": "Re-Logic", "publisher": "Re-Logic", "release_date": "2011-05-16", "price_usd": 9.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch", "Mobile"], "tags": ["Sandbox", "Survival", "2D"], "short_description": "Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/108600/header.jpg", "store_link": "https://store.steampowered.com/app/108600/"},
        {"id": "g_275850", "steam_app_id": 275850, "title": "No Man's Sky", "developer": "Hello Games", "publisher": "Hello Games", "release_date": "2016-08-12", "price_usd": 59.99, "rating": 90, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["Space", "Exploration", "Survival"], "short_description": "Explore an infinite universe of unique planets and lifeforms.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/275850/header.jpg", "store_link": "https://store.steampowered.com/app/275850/"},
        {"id": "g_1250410", "steam_app_id": 1250410, "title": "Microsoft Flight Simulator", "developer": "Asobo Studio", "publisher": "Xbox Game Studios", "release_date": "2021-07-27", "price_usd": 59.99, "rating": 92, "platforms": ["Windows", "Xbox"], "tags": ["Flight Sim", "Realistic", "Exploration"], "short_description": "Explore the world with unprecedented realism in this next-gen flight simulator.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1250410/header.jpg", "store_link": "https://store.steampowered.com/app/1250410/"}
      ]
    },
    {
      "id": "cat_free_to_play",
      "name": "Free to Play",
      "slug": "free-to-play",
      "description": "No upfront cost—jump in and enjoy these free gaming experiences.",
      "games": [
        {"id": "g_730", "steam_app_id": 730, "title": "Counter-Strike 2", "developer": "Valve", "publisher": "Valve", "release_date": "2023-09-27", "price_usd": 0.00, "rating": 85, "platforms": ["Windows", "Linux"], "tags": ["FPS", "Competitive", "Tactical"], "short_description": "For over two decades, Counter-Strike has offered an elite competitive experience.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg", "store_link": "https://store.steampowered.com/app/730/"},
        {"id": "g_570", "steam_app_id": 570, "title": "Dota 2", "developer": "Valve", "publisher": "Valve", "release_date": "2013-07-09", "price_usd": 0.00, "rating": 86, "platforms": ["Windows", "macOS", "Linux"], "tags": ["MOBA", "Strategy", "Multiplayer"], "short_description": "Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg", "store_link": "https://store.steampowered.com/app/570/"},
        {"id": "g_440", "steam_app_id": 440, "title": "Team Fortress 2", "developer": "Valve", "publisher": "Valve", "release_date": "2007-10-10", "price_usd": 0.00, "rating": 92, "platforms": ["Windows", "macOS", "Linux"], "tags": ["FPS", "Class-Based", "Comedy"], "short_description": "Nine distinct classes provide a broad range of tactical abilities and characters.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/440/header.jpg", "store_link": "https://store.steampowered.com/app/440/"},
        {"id": "g_578080", "steam_app_id": 578080, "title": "PUBG: BATTLEGROUNDS", "developer": "KRAFTON, Inc.", "publisher": "KRAFTON, Inc.", "release_date": "2017-12-21", "price_usd": 0.00, "rating": 80, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Battle Royale", "FPS", "Survival"], "short_description": "Land on strategic locations, loot weapons and supplies, and survive to become the last team standing.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/578080/header.jpg", "store_link": "https://store.steampowered.com/app/578080/"}
      ]
    },
    {
      "id": "cat_early_access",
      "name": "Early Access",
      "slug": "early-access",
      "description": "Games in development—play now and help shape their future.",
      "games": [
        {"id": "g_251570", "steam_app_id": 251570, "title": "7 Days to Die", "developer": "The Fun Pimps", "publisher": "The Fun Pimps Entertainment LLC", "release_date": "2024-07-25", "price_usd": 44.99, "rating": 89, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Survival", "Zombies", "Crafting"], "short_description": "A brutal zombie survival game with deep crafting and building mechanics.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/251570/header.jpg", "store_link": "https://store.steampowered.com/app/251570/"},
        {"id": "g_1144200", "steam_app_id": 1144200, "title": "Ready or Not", "developer": "VOID Interactive", "publisher": "VOID Interactive", "release_date": "2023-12-13", "price_usd": 49.99, "rating": 93, "platforms": ["Windows"], "tags": ["Tactical", "FPS", "Realistic"], "short_description": "A tactical first-person shooter that simulates real-world police operations.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1144200/header.jpg", "store_link": "https://store.steampowered.com/app/1144200/"},
        {"id": "g_648800", "steam_app_id": 648800, "title": "Raft", "developer": "Redbeet Interactive", "publisher": "Axolot Games", "release_date": "2022-06-20", "price_usd": 19.99, "rating": 93, "platforms": ["Windows"], "tags": ["Survival", "Co-op", "Ocean"], "short_description": "Survive on a raft in an endless ocean, gathering debris and fighting off sharks.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/648800/header.jpg", "store_link": "https://store.steampowered.com/app/648800/"},
        {"id": "g_252490", "steam_app_id": 252490, "title": "Rust", "developer": "Facepunch Studios", "publisher": "Facepunch Studios", "release_date": "2018-02-08", "price_usd": 39.99, "rating": 88, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox"], "tags": ["Survival", "Multiplayer", "PvP"], "short_description": "The only aim in Rust is to survive. Everything wants you to die.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg", "store_link": "https://store.steampowered.com/app/252490/"}
      ]
    },
    {
      "id": "cat_narrative_story_driven",
      "name": "Narrative & Story-Driven",
      "slug": "narrative-story-driven",
      "description": "Rich storytelling, compelling characters, and emotional journeys.",
      "games": [
        {"id": "g_1174180", "steam_app_id": 1174180, "title": "Red Dead Redemption 2", "developer": "Rockstar Games", "publisher": "Rockstar Games", "release_date": "2019-11-05", "price_usd": 59.99, "rating": 94, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Western", "Open World", "Story Rich"], "short_description": "America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg", "store_link": "https://store.steampowered.com/app/1174180/"},
        {"id": "g_292030", "steam_app_id": 292030, "title": "The Witcher 3: Wild Hunt", "developer": "CD PROJEKT RED", "publisher": "CD PROJEKT RED", "release_date": "2015-05-18", "price_usd": 39.99, "rating": 98, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["RPG", "Open World", "Fantasy"], "short_description": "Play as a highly trained monster slayer for hire in this massive, story-driven RPG.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg", "store_link": "https://store.steampowered.com/app/292030/"},
        {"id": "g_1086940", "steam_app_id": 1086940, "title": "Baldur's Gate 3", "developer": "Larian Studios", "publisher": "Larian Studios", "release_date": "2023-08-03", "price_usd": 59.99, "rating": 98, "platforms": ["Windows", "macOS", "PlayStation"], "tags": ["D&D", "Turn-Based", "Co-op"], "short_description": "Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg", "store_link": "https://store.steampowered.com/app/1086940/"},
        {"id": "g_1593500", "steam_app_id": 1593500, "title": "God of War", "developer": "Santa Monica Studio", "publisher": "PlayStation PC LLC", "release_date": "2022-01-14", "price_usd": 49.99, "rating": 97, "platforms": ["Windows", "PlayStation"], "tags": ["Hack and Slash", "Mythology", "Story Rich"], "short_description": "Kratos must adapt to an unfamiliar world as he fights to save his son.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/header.jpg", "store_link": "https://store.steampowered.com/app/1593500/"}
      ]
    },
    {
      "id": "cat_atmospheric",
      "name": "Atmospheric",
      "slug": "atmospheric",
      "description": "Immersive worlds with stunning visuals, sound design, and mood.",
      "games": [
        {"id": "g_1245620", "steam_app_id": 1245620, "title": "Elden Ring", "developer": "FromSoftware", "publisher": "Bandai Namco", "release_date": "2022-02-25", "price_usd": 59.99, "rating": 96, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Souls-like", "Open World", "Dark Fantasy"], "short_description": "A sprawling action RPG set in the Lands Between, created by Miyazaki and Martin.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg", "store_link": "https://store.steampowered.com/app/1245620/"},
        {"id": "g_292030", "steam_app_id": 292030, "title": "The Witcher 3: Wild Hunt", "developer": "CD PROJEKT RED", "publisher": "CD PROJEKT RED", "release_date": "2015-05-18", "price_usd": 39.99, "rating": 98, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["RPG", "Open World", "Fantasy"], "short_description": "Play as a highly trained monster slayer for hire in this massive, story-driven RPG.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg", "store_link": "https://store.steampowered.com/app/292030/"},
        {"id": "g_1091500", "steam_app_id": 1091500, "title": "Cyberpunk 2077", "developer": "CD PROJEKT RED", "publisher": "CD PROJEKT RED", "release_date": "2020-12-10", "price_usd": 59.99, "rating": 92, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Cyberpunk", "RPG", "Open World"], "short_description": "Become V, a cyberpunk mercenary in Night City, a megalopolis obsessed with power.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg", "store_link": "https://store.steampowered.com/app/1091500/"},
        {"id": "g_1174180", "steam_app_id": 1174180, "title": "Red Dead Redemption 2", "developer": "Rockstar Games", "publisher": "Rockstar Games", "release_date": "2019-11-05", "price_usd": 59.99, "rating": 94, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Western", "Open World", "Story Rich"], "short_description": "America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg", "store_link": "https://store.steampowered.com/app/1174180/"}
      ]
    },
    {
      "id": "cat_dark_fantasy",
      "name": "Dark Fantasy",
      "slug": "dark-fantasy",
      "description": "Grim worlds, challenging combat, and mature themes in fantasy settings.",
      "games": [
        {"id": "g_1245620", "steam_app_id": 1245620, "title": "Elden Ring", "developer": "FromSoftware", "publisher": "Bandai Namco", "release_date": "2022-02-25", "price_usd": 59.99, "rating": 96, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Souls-like", "Open World", "Dark Fantasy"], "short_description": "A sprawling action RPG set in the Lands Between, created by Miyazaki and Martin.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg", "store_link": "https://store.steampowered.com/app/1245620/"},
        {"id": "g_814380", "steam_app_id": 814380, "title": "Sekiro: Shadows Die Twice", "developer": "FromSoftware", "publisher": "Activision", "release_date": "2019-03-22", "price_usd": 59.99, "rating": 95, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Souls-like", "Action", "Stealth"], "short_description": "Carve your own clever path to vengeance in an all-new adventure from FromSoftware.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/814380/header.jpg", "store_link": "https://store.steampowered.com/app/814380/"},
        {"id": "g_367520", "steam_app_id": 367520, "title": "Hollow Knight", "developer": "Team Cherry", "publisher": "Team Cherry", "release_date": "2017-02-24", "price_usd": 14.99, "rating": 99, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["Metroidvania", "Souls-like", "Indie"], "short_description": "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg", "store_link": "https://store.steampowered.com/app/367520/"},
        {"id": "g_292030", "steam_app_id": 292030, "title": "The Witcher 3: Wild Hunt", "developer": "CD PROJEKT RED", "publisher": "CD PROJEKT RED", "release_date": "2015-05-18", "price_usd": 39.99, "rating": 98, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["RPG", "Open World", "Fantasy"], "short_description": "Play as a highly trained monster slayer for hire in this massive, story-driven RPG.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg", "store_link": "https://store.steampowered.com/app/292030/"}
      ]
    },
    {
      "id": "cat_sci_fi",
      "name": "Sci-Fi",
      "slug": "sci-fi",
      "description": "Futuristic settings, advanced technology, and space exploration.",
      "games": [
        {"id": "g_1091500", "steam_app_id": 1091500, "title": "Cyberpunk 2077", "developer": "CD PROJEKT RED", "publisher": "CD PROJEKT RED", "release_date": "2020-12-10", "price_usd": 59.99, "rating": 92, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Cyberpunk", "RPG", "Open World"], "short_description": "Become V, a cyberpunk mercenary in Night City, a megalopolis obsessed with power.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg", "store_link": "https://store.steampowered.com/app/1091500/"},
        {"id": "g_1716740", "steam_app_id": 1716740, "title": "Starfield", "developer": "Bethesda Game Studios", "publisher": "Bethesda Softworks", "release_date": "2023-09-06", "price_usd": 69.99, "rating": 85, "platforms": ["Windows", "Xbox"], "tags": ["Space", "Open World", "Sci-Fi"], "short_description": "The next generation space RPG from Bethesda, featuring over 1000 planets.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1716740/header.jpg", "store_link": "https://store.steampowered.com/app/1716740/"},
        {"id": "g_275850", "steam_app_id": 275850, "title": "No Man's Sky", "developer": "Hello Games", "publisher": "Hello Games", "release_date": "2016-08-12", "price_usd": 59.99, "rating": 90, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["Space", "Exploration", "Survival"], "short_description": "Explore an infinite universe of unique planets and lifeforms.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/275850/header.jpg", "store_link": "https://store.steampowered.com/app/275850/"},
        {"id": "g_291480", "steam_app_id": 291480, "title": "RimWorld", "developer": "Ludeon Studios", "publisher": "Ludeon Studios", "release_date": "2018-10-17", "price_usd": 34.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux"], "tags": ["Colony Sim", "Sci-Fi", "Story Generator"], "short_description": "A sci-fi colony sim driven by an intelligent AI storyteller.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/291480/header.jpg", "store_link": "https://store.steampowered.com/app/291480/"}
      ]
    },
    {
      "id": "cat_fantasy",
      "name": "Fantasy",
      "slug": "fantasy",
      "description": "Magical worlds, mythical creatures, and epic quests.",
      "games": [
        {"id": "g_292030", "steam_app_id": 292030, "title": "The Witcher 3: Wild Hunt", "developer": "CD PROJEKT RED", "publisher": "CD PROJEKT RED", "release_date": "2015-05-18", "price_usd": 39.99, "rating": 98, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["RPG", "Open World", "Fantasy"], "short_description": "Play as a highly trained monster slayer for hire in this massive, story-driven RPG.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg", "store_link": "https://store.steampowered.com/app/292030/"},
        {"id": "g_1245620", "steam_app_id": 1245620, "title": "Elden Ring", "developer": "FromSoftware", "publisher": "Bandai Namco", "release_date": "2022-02-25", "price_usd": 59.99, "rating": 96, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Souls-like", "Open World", "Dark Fantasy"], "short_description": "A sprawling action RPG set in the Lands Between, created by Miyazaki and Martin.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg", "store_link": "https://store.steampowered.com/app/1245620/"},
        {"id": "g_1086940", "steam_app_id": 1086940, "title": "Baldur's Gate 3", "developer": "Larian Studios", "publisher": "Larian Studios", "release_date": "2023-08-03", "price_usd": 59.99, "rating": 98, "platforms": ["Windows", "macOS", "PlayStation"], "tags": ["D&D", "Turn-Based", "Co-op"], "short_description": "Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg", "store_link": "https://store.steampowered.com/app/1086940/"},
        {"id": "g_489830", "steam_app_id": 489830, "title": "The Elder Scrolls V: Skyrim Special Edition", "developer": "Bethesda Game Studios", "publisher": "Bethesda Softworks", "release_date": "2016-10-27", "price_usd": 39.99, "rating": 95, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["Open World", "Fantasy", "Moddable"], "short_description": "Winner of more than 200 Game of the Year Awards, Skyrim SE brings the epic fantasy to life.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/489830/header.jpg", "store_link": "https://store.steampowered.com/app/489830/"}
      ]
    },
    {
      "id": "cat_historical",
      "name": "Historical",
      "slug": "historical",
      "description": "Journey through time with historically-inspired settings and events.",
      "games": [
        {"id": "g_1174180", "steam_app_id": 1174180, "title": "Red Dead Redemption 2", "developer": "Rockstar Games", "publisher": "Rockstar Games", "release_date": "2019-11-05", "price_usd": 59.99, "rating": 94, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Western", "Open World", "Story Rich"], "short_description": "America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg", "store_link": "https://store.steampowered.com/app/1174180/"},
        {"id": "g_289070", "steam_app_id": 289070, "title": "Sid Meier's Civilization VI", "developer": "Firaxis Games", "publisher": "2K", "release_date": "2016-10-21", "price_usd": 59.99, "rating": 94, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["4X", "Turn-Based Strategy", "Historical"], "short_description": "Build an empire to stand the test of time in this award-winning strategy masterpiece.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/289070/header.jpg", "store_link": "https://store.steampowered.com/app/289070/"},
        {"id": "g_271590", "steam_app_id": 271590, "title": "Grand Theft Auto V", "developer": "Rockstar North", "publisher": "Rockstar Games", "release_date": "2015-04-14", "price_usd": 29.99, "rating": 90, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Open World", "Action", "Multiplayer"], "short_description": "Experience the sprawling world of Los Santos in this massive open-world action game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg", "store_link": "https://store.steampowered.com/app/271590/"},
        {"id": "g_1086940", "steam_app_id": 1086940, "title": "Baldur's Gate 3", "developer": "Larian Studios", "publisher": "Larian Studios", "release_date": "2023-08-03", "price_usd": 59.99, "rating": 98, "platforms": ["Windows", "macOS", "PlayStation"], "tags": ["D&D", "Turn-Based", "Co-op"], "short_description": "Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg", "store_link": "https://store.steampowered.com/app/1086940/"}
      ]
    },
    {
      "id": "cat_modern",
      "name": "Modern",
      "slug": "modern",
      "description": "Contemporary settings with realistic or near-future scenarios.",
      "games": [
        {"id": "g_271590", "steam_app_id": 271590, "title": "Grand Theft Auto V", "developer": "Rockstar North", "publisher": "Rockstar Games", "release_date": "2015-04-14", "price_usd": 29.99, "rating": 90, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Open World", "Action", "Multiplayer"], "short_description": "Experience the sprawling world of Los Santos in this massive open-world action game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg", "store_link": "https://store.steampowered.com/app/271590/"},
        {"id": "g_1091500", "steam_app_id": 1091500, "title": "Cyberpunk 2077", "developer": "CD PROJEKT RED", "publisher": "CD PROJEKT RED", "release_date": "2020-12-10", "price_usd": 59.99, "rating": 92, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Cyberpunk", "RPG", "Open World"], "short_description": "Become V, a cyberpunk mercenary in Night City, a megalopolis obsessed with power.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg", "store_link": "https://store.steampowered.com/app/1091500/"},
        {"id": "g_730", "steam_app_id": 730, "title": "Counter-Strike 2", "developer": "Valve", "publisher": "Valve", "release_date": "2023-09-27", "price_usd": 0.00, "rating": 85, "platforms": ["Windows", "Linux"], "tags": ["FPS", "Competitive", "Tactical"], "short_description": "For over two decades, Counter-Strike has offered an elite competitive experience.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg", "store_link": "https://store.steampowered.com/app/730/"},
        {"id": "g_359550", "steam_app_id": 359550, "title": "Tom Clancy's Rainbow Six Siege", "developer": "Ubisoft Montreal", "publisher": "Ubisoft", "release_date": "2015-12-01", "price_usd": 19.99, "rating": 87, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Tactical", "FPS", "Destruction"], "short_description": "Master the art of destruction as you lead your team in intense close-quarters combat.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/359550/header.jpg", "store_link": "https://store.steampowered.com/app/359550/"}
      ]
    },
    {
      "id": "cat_post_apocalyptic",
      "name": "Post-Apocalyptic",
      "slug": "post-apocalyptic",
      "description": "Survive in a world after civilization has collapsed.",
      "games": [
        {"id": "g_242760", "steam_app_id": 242760, "title": "The Forest", "developer": "Endnight Games Ltd", "publisher": "Endnight Games Ltd", "release_date": "2018-04-30", "price_usd": 19.99, "rating": 94, "platforms": ["Windows"], "tags": ["Survival", "Horror", "Open World"], "short_description": "Survive a plane crash in a forest filled with cannibalistic mutants.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/242760/header.jpg", "store_link": "https://store.steampowered.com/app/242760/"},
        {"id": "g_251570", "steam_app_id": 251570, "title": "7 Days to Die", "developer": "The Fun Pimps", "publisher": "The Fun Pimps Entertainment LLC", "release_date": "2024-07-25", "price_usd": 44.99, "rating": 89, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Survival", "Zombies", "Crafting"], "short_description": "A brutal zombie survival game with deep crafting and building mechanics.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/251570/header.jpg", "store_link": "https://store.steampowered.com/app/251570/"},
        {"id": "g_252490", "steam_app_id": 252490, "title": "Rust", "developer": "Facepunch Studios", "publisher": "Facepunch Studios", "release_date": "2018-02-08", "price_usd": 39.99, "rating": 88, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox"], "tags": ["Survival", "Multiplayer", "PvP"], "short_description": "The only aim in Rust is to survive. Everything wants you to die.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg", "store_link": "https://store.steampowered.com/app/252490/"},
        {"id": "g_304930", "steam_app_id": 304930, "title": "Unturned", "developer": "Smartly Dressed Games", "publisher": "Smartly Dressed Games", "release_date": "2017-07-07", "price_usd": 0.00, "rating": 91, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["Survival", "Zombies", "Free to Play"], "short_description": "A free-to-play sandbox survival game with blocky graphics and deep mechanics.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/304930/header.jpg", "store_link": "https://store.steampowered.com/app/304930/"}
      ]
    },
    {
      "id": "cat_zombies",
      "name": "Zombies",
      "slug": "zombies",
      "description": "Fight off hordes of undead in these zombie-focused games.",
      "games": [
        {"id": "g_251570", "steam_app_id": 251570, "title": "7 Days to Die", "developer": "The Fun Pimps", "publisher": "The Fun Pimps Entertainment LLC", "release_date": "2024-07-25", "price_usd": 44.99, "rating": 89, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Survival", "Zombies", "Crafting"], "short_description": "A brutal zombie survival game with deep crafting and building mechanics.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/251570/header.jpg", "store_link": "https://store.steampowered.com/app/251570/"},
        {"id": "g_304930", "steam_app_id": 304930, "title": "Unturned", "developer": "Smartly Dressed Games", "publisher": "Smartly Dressed Games", "release_date": "2017-07-07", "price_usd": 0.00, "rating": 91, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["Survival", "Zombies", "Free to Play"], "short_description": "A free-to-play sandbox survival game with blocky graphics and deep mechanics.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/304930/header.jpg", "store_link": "https://store.steampowered.com/app/304930/"},
        {"id": "g_242760", "steam_app_id": 242760, "title": "The Forest", "developer": "Endnight Games Ltd", "publisher": "Endnight Games Ltd", "release_date": "2018-04-30", "price_usd": 19.99, "rating": 94, "platforms": ["Windows"], "tags": ["Survival", "Horror", "Open World"], "short_description": "Survive a plane crash in a forest filled with cannibalistic mutants.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/242760/header.jpg", "store_link": "https://store.steampowered.com/app/242760/"},
        {"id": "g_252490", "steam_app_id": 252490, "title": "Rust", "developer": "Facepunch Studios", "publisher": "Facepunch Studios", "release_date": "2018-02-08", "price_usd": 39.99, "rating": 88, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox"], "tags": ["Survival", "Multiplayer", "PvP"], "short_description": "The only aim in Rust is to survive. Everything wants you to die.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/252490/header.jpg", "store_link": "https://store.steampowered.com/app/252490/"}
      ]
    },
    {
      "id": "cat_pirates",
      "name": "Pirates",
      "slug": "pirates",
      "description": "Sail the seas, plunder treasure, and live the pirate life.",
      "games": [
        {"id": "g_1172620", "steam_app_id": 1172620, "title": "Sea of Thieves", "developer": "Rare", "publisher": "Xbox Game Studios", "release_date": "2020-06-03", "price_usd": 39.99, "rating": 88, "platforms": ["Windows", "Xbox"], "tags": ["Pirates", "Open World", "Co-op"], "short_description": "A shared-world adventure game that lets you sail the seas as a pirate.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1172620/header.jpg", "store_link": "https://store.steampowered.com/app/1172620/"},
        {"id": "g_648800", "steam_app_id": 648800, "title": "Raft", "developer": "Redbeet Interactive", "publisher": "Axolot Games", "release_date": "2022-06-20", "price_usd": 19.99, "rating": 93, "platforms": ["Windows"], "tags": ["Survival", "Co-op", "Ocean"], "short_description": "Survive on a raft in an endless ocean, gathering debris and fighting off sharks.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/648800/header.jpg", "store_link": "https://store.steampowered.com/app/648800/"},
        {"id": "g_271590", "steam_app_id": 271590, "title": "Grand Theft Auto V", "developer": "Rockstar North", "publisher": "Rockstar Games", "release_date": "2015-04-14", "price_usd": 29.99, "rating": 90, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Open World", "Action", "Multiplayer"], "short_description": "Experience the sprawling world of Los Santos in this massive open-world action game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg", "store_link": "https://store.steampowered.com/app/271590/"},
        {"id": "g_1085660", "steam_app_id": 1085660, "title": "Destiny 2", "developer": "Bungie", "publisher": "Bungie", "release_date": "2019-10-01", "price_usd": 0.00, "rating": 85, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["FPS", "Looter Shooter", "Free to Play"], "short_description": "A free-to-play action MMO with a shared world and seamless matchmaking.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1085660/header.jpg", "store_link": "https://store.steampowered.com/app/1085660/"}
      ]
    },
    {
      "id": "cat_space_flight",
      "name": "Space & Flight",
      "slug": "space-flight",
      "description": "Explore the cosmos or take to the skies in these flight and space games.",
      "games": [
        {"id": "g_1716740", "steam_app_id": 1716740, "title": "Starfield", "developer": "Bethesda Game Studios", "publisher": "Bethesda Softworks", "release_date": "2023-09-06", "price_usd": 69.99, "rating": 85, "platforms": ["Windows", "Xbox"], "tags": ["Space", "Open World", "Sci-Fi"], "short_description": "The next generation space RPG from Bethesda, featuring over 1000 planets.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1716740/header.jpg", "store_link": "https://store.steampowered.com/app/1716740/"},
        {"id": "g_275850", "steam_app_id": 275850, "title": "No Man's Sky", "developer": "Hello Games", "publisher": "Hello Games", "release_date": "2016-08-12", "price_usd": 59.99, "rating": 90, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["Space", "Exploration", "Survival"], "short_description": "Explore an infinite universe of unique planets and lifeforms.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/275850/header.jpg", "store_link": "https://store.steampowered.com/app/275850/"},
        {"id": "g_1250410", "steam_app_id": 1250410, "title": "Microsoft Flight Simulator", "developer": "Asobo Studio", "publisher": "Xbox Game Studios", "release_date": "2021-07-27", "price_usd": 59.99, "rating": 92, "platforms": ["Windows", "Xbox"], "tags": ["Flight Sim", "Realistic", "Exploration"], "short_description": "Explore the world with unprecedented realism in this next-gen flight simulator.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1250410/header.jpg", "store_link": "https://store.steampowered.com/app/1250410/"},
        {"id": "g_236390", "steam_app_id": 236390, "title": "War Thunder", "developer": "Gaijin Entertainment", "publisher": "Gaijin Entertainment", "release_date": "2013-08-15", "price_usd": 0.00, "rating": 78, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox"], "tags": ["Vehicular Combat", "Flight Sim", "Free to Play"], "short_description": "The most comprehensive free-to-play military game featuring aviation, armor, and fleets.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/236390/header.jpg", "store_link": "https://store.steampowered.com/app/236390/"}
      ]
    },
    {
      "id": "cat_military_war",
      "name": "Military & War",
      "slug": "military-war",
      "description": "Tactical combat, military operations, and war-themed experiences.",
      "games": [
        {"id": "g_730", "steam_app_id": 730, "title": "Counter-Strike 2", "developer": "Valve", "publisher": "Valve", "release_date": "2023-09-27", "price_usd": 0.00, "rating": 85, "platforms": ["Windows", "Linux"], "tags": ["FPS", "Competitive", "Tactical"], "short_description": "For over two decades, Counter-Strike has offered an elite competitive experience.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg", "store_link": "https://store.steampowered.com/app/730/"},
        {"id": "g_359550", "steam_app_id": 359550, "title": "Tom Clancy's Rainbow Six Siege", "developer": "Ubisoft Montreal", "publisher": "Ubisoft", "release_date": "2015-12-01", "price_usd": 19.99, "rating": 87, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Tactical", "FPS", "Destruction"], "short_description": "Master the art of destruction as you lead your team in intense close-quarters combat.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/359550/header.jpg", "store_link": "https://store.steampowered.com/app/359550/"},
        {"id": "g_1144200", "steam_app_id": 1144200, "title": "Ready or Not", "developer": "VOID Interactive", "publisher": "VOID Interactive", "release_date": "2023-12-13", "price_usd": 49.99, "rating": 93, "platforms": ["Windows"], "tags": ["Tactical", "FPS", "Realistic"], "short_description": "A tactical first-person shooter that simulates real-world police operations.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1144200/header.jpg", "store_link": "https://store.steampowered.com/app/1144200/"},
        {"id": "g_236390", "steam_app_id": 236390, "title": "War Thunder", "developer": "Gaijin Entertainment", "publisher": "Gaijin Entertainment", "release_date": "2013-08-15", "price_usd": 0.00, "rating": 78, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox"], "tags": ["Vehicular Combat", "Flight Sim", "Free to Play"], "short_description": "The most comprehensive free-to-play military game featuring aviation, armor, and fleets.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/236390/header.jpg", "store_link": "https://store.steampowered.com/app/236390/"}
      ]
    },
    {
      "id": "cat_detective_mystery",
      "name": "Detective & Mystery",
      "slug": "detective-mystery",
      "description": "Solve crimes, uncover secrets, and piece together clues.",
      "games": [
        {"id": "g_1086940", "steam_app_id": 1086940, "title": "Baldur's Gate 3", "developer": "Larian Studios", "publisher": "Larian Studios", "release_date": "2023-08-03", "price_usd": 59.99, "rating": 98, "platforms": ["Windows", "macOS", "PlayStation"], "tags": ["D&D", "Turn-Based", "Co-op"], "short_description": "Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg", "store_link": "https://store.steampowered.com/app/1086940/"},
        {"id": "g_292030", "steam_app_id": 292030, "title": "The Witcher 3: Wild Hunt", "developer": "CD PROJEKT RED", "publisher": "CD PROJEKT RED", "release_date": "2015-05-18", "price_usd": 39.99, "rating": 98, "platforms": ["Windows", "PlayStation", "Xbox", "Switch"], "tags": ["RPG", "Open World", "Fantasy"], "short_description": "Play as a highly trained monster slayer for hire in this massive, story-driven RPG.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg", "store_link": "https://store.steampowered.com/app/292030/"},
        {"id": "g_1174180", "steam_app_id": 1174180, "title": "Red Dead Redemption 2", "developer": "Rockstar Games", "publisher": "Rockstar Games", "release_date": "2019-11-05", "price_usd": 59.99, "rating": 94, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Western", "Open World", "Story Rich"], "short_description": "America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg", "store_link": "https://store.steampowered.com/app/1174180/"},
        {"id": "g_271590", "steam_app_id": 271590, "title": "Grand Theft Auto V", "developer": "Rockstar North", "publisher": "Rockstar Games", "release_date": "2015-04-14", "price_usd": 29.99, "rating": 90, "platforms": ["Windows", "PlayStation", "Xbox"], "tags": ["Open World", "Action", "Multiplayer"], "short_description": "Experience the sprawling world of Los Santos in this massive open-world action game.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg", "store_link": "https://store.steampowered.com/app/271590/"}
      ]
    },
    {
      "id": "cat_comedy",
      "name": "Comedy",
      "slug": "comedy",
      "description": "Humorous gameplay, witty dialogue, and laugh-out-loud moments.",
      "games": [
        {"id": "g_440", "steam_app_id": 440, "title": "Team Fortress 2", "developer": "Valve", "publisher": "Valve", "release_date": "2007-10-10", "price_usd": 0.00, "rating": 92, "platforms": ["Windows", "macOS", "Linux"], "tags": ["FPS", "Class-Based", "Comedy"], "short_description": "Nine distinct classes provide a broad range of tactical abilities and characters.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/440/header.jpg", "store_link": "https://store.steampowered.com/app/440/"},
        {"id": "g_105600", "steam_app_id": 105600, "title": "Portal 2", "developer": "Valve", "publisher": "Valve", "release_date": "2011-04-19", "price_usd": 9.99, "rating": 99, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox"], "tags": ["Puzzle", "FPS", "Story Rich"], "short_description": "The 'Perpetual Testing Initiative' has been expanded to allow you to design co-op puzzles!", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/105600/header.jpg", "store_link": "https://store.steampowered.com/app/105600/"},
        {"id": "g_620", "steam_app_id": 620, "title": "Portal", "developer": "Valve", "publisher": "Valve", "release_date": "2007-10-10", "price_usd": 9.99, "rating": 99, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch"], "tags": ["Puzzle", "FPS", "Sci-Fi"], "short_description": "A pioneering first-person puzzle game that redefined the genre.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg", "store_link": "https://store.steampowered.com/app/620/"},
        {"id": "g_413150", "steam_app_id": 413150, "title": "Stardew Valley", "developer": "ConcernedApe", "publisher": "ConcernedApe", "release_date": "2016-02-26", "price_usd": 14.99, "rating": 98, "platforms": ["Windows", "macOS", "Linux", "PlayStation", "Xbox", "Switch", "Mobile"], "tags": ["Farming Sim", "Relaxing", "Pixel Graphics"], "short_description": "Move to the countryside, cultivate a new life, and restore the old farm.", "image": "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg", "store_link": "https://store.steampowered.com/app/413150/"}
      ]
    }
  ]