export const gameFields = [
    {
        name: 'title',
        label: 'Title',
        type: 'text',
        placeholder: 'Enter game title',
        required: true,
    },
    {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        placeholder: 'Enter game description',
        required: true,
    },
    {
        name: 'genre',
        label: 'Genre',
        type: 'text',
        placeholder: 'Enter game genre',
        required: true,
    },
    {
        name: 'thumbnail',
        label: 'Thumbnail URL',
        type: 'text',
        placeholder: 'Enter image URL (e.g. https://.../image.png)',
        required: true,
    },
    {
        name: 'iframeUrl',
        label: 'Game URL',
        type: 'text',
        placeholder: 'Enter game iframe URL',
        required: true,
    },
    {
        name: 'developer',
        label: 'Developer',
        type: 'text',
        placeholder: 'Enter developer name',
        required: false,
    },
    {
        name: 'releaseDate',
        label: 'Release Date',
        type: 'text',
        placeholder: 'e.g. 2024',
        required: false,
    },
    {
        name: 'controls',
        label: 'Controls',
        type: 'text',
        placeholder: 'e.g. Arrow Keys / Mouse / Touch',
        required: false,
    },
    {
        name: 'rating',
        label: 'Rating',
        type: 'number',
        placeholder: 'Enter rating (0-5)',
        required: false,
    },
    {
        name: 'featured',
        label: 'Featured Game',
        type: 'checkbox',
        required: false,
    },
];